<template>
  <section><div class="page-heading"><div><div class="eyebrow">管理员权限 / Approval queue</div><h1>审批中心</h1><p>批准与拒绝都会记录审计；拒绝时必须说明原因。未批准资产不可导出。</p></div></div>
  <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon class="notice" />
  <el-tabs v-model="tab"><el-tab-pane label="内容包审批" name="content"><div class="panel"><el-table :data="pendingPackages" empty-text="没有待审批内容包"><el-table-column prop="product_name" label="商品"/><el-table-column label="事实版本"><template #default="{row}"><span class="fact">{{ row.fact_version }}</span></template></el-table-column><el-table-column prop="version" label="版本" width="80"><template #default="{row}">v{{ row.version }}</template></el-table-column><el-table-column prop="updated_at" label="提交时间" width="180"/><el-table-column label="操作" width="220"><template #default="{row}"><el-button type="success" link @click="packageAction(row,'approve')">批准</el-button><el-button type="danger" link @click="openReject('package',row.id)">拒绝</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane label="图片审批" name="image"><div class="panel"><el-table :data="pendingTasks" empty-text="没有待审批图片"><el-table-column prop="product_name" label="商品"/><el-table-column prop="reference_name" label="参考图"/><el-table-column label="确认状态"><template #default="{row}"><el-tag :type="row.confirmed?'success':'warning'">{{ row.confirmed?'已人工确认':'未确认' }}</el-tag></template></el-table-column><el-table-column label="操作" width="220"><template #default="{row}"><el-button type="success" link :disabled="!row.confirmed" @click="taskAction(row,'approve')">批准</el-button><el-button type="danger" link @click="openReject('task',row.id)">拒绝</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane label="审计摘要" name="audit"><div class="panel"><el-table :data="audits" empty-text="暂无本次会话审计事件"><el-table-column prop="at" label="时间" width="180"/><el-table-column prop="action" label="事件" width="180"/><el-table-column prop="target" label="对象" width="180"/><el-table-column prop="summary" label="摘要"/></el-table></div></el-tab-pane></el-tabs>
  <el-dialog v-model="rejectOpen" title="拒绝审批" width="440px"><p>拒绝原因将写入审批记录与审计事件。</p><el-input v-model="reason" type="textarea" :rows="4" placeholder="请填写拒绝原因"/><template #footer><el-button @click="rejectOpen=false">取消</el-button><el-button type="danger" :disabled="!reason.trim()" @click="reject">确认拒绝</el-button></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue"; import { ElMessage } from "element-plus"; import { errorMessage } from "../api/client"; import { m2Api, type AuditEvent, type ContentPackage, type ImageTask } from "../api/milestone2";
const tab=ref("content"),packages=ref<ContentPackage[]>([]),tasks=ref<ImageTask[]>([]),audits=ref<AuditEvent[]>([]),error=ref(""),rejectOpen=ref(false),reason=ref(""),rejectTarget=ref<{kind:"package"|"task";id:number}>();
const pendingPackages=computed(()=>packages.value.filter(x=>x.status==="submitted"));const pendingTasks=computed(()=>tasks.value.filter(x=>x.approval_status==="submitted"));
async function refresh(){try{[packages.value,tasks.value,audits.value]=await Promise.all([m2Api.listPackages(),m2Api.listTasks(),m2Api.listAudits()])}catch(e){error.value=errorMessage(e)}}
async function packageAction(item:ContentPackage,action:"approve"){try{await m2Api.packageAction(item.id,action);await refresh();ElMessage.success("内容包已批准")}catch(e){error.value=errorMessage(e)}}
async function taskAction(item:ImageTask,action:"approve"){try{await m2Api.taskAction(item.id,action);await refresh();ElMessage.success("图片已批准")}catch(e){error.value=errorMessage(e)}}
function openReject(kind:"package"|"task",id:number){rejectTarget.value={kind,id};reason.value="";rejectOpen.value=true}
async function reject(){if(!rejectTarget.value||!reason.value.trim())return;try{const t=rejectTarget.value;if(t.kind==="package")await m2Api.packageAction(t.id,"reject",reason.value.trim());else await m2Api.taskAction(t.id,"reject",reason.value.trim());rejectOpen.value=false;await refresh();ElMessage.success("已拒绝并记录原因")}catch(e){error.value=errorMessage(e)}}
watch(tab,()=>{if(tab.value==="audit")refresh()});onMounted(refresh);
</script>
<style scoped>.notice{margin-bottom:14px}.fact{font-family:monospace;color:var(--green)}</style>
