<template>
  <section><div class="page-heading"><div><div class="eyebrow">人工确认 / Image task</div><h1>图片任务</h1><p>先上传参考图，再创建任务；生成结果必须人工确认、审批后才可导出。</p></div></div>
  <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon class="notice" />
  <div class="new-task panel"><div><b>创建图片任务</b><p>商品必须为已批准状态。参考图是创建任务的前置条件。</p></div><el-upload :auto-upload="false" :show-file-list="false" accept="image/png,image/jpeg,image/webp" @change="onFile"><el-button>上传参考图</el-button></el-upload><span class="file-name">{{ referenceName || '未选择参考图' }}</span><el-input v-model="prompt" placeholder="图片任务说明" class="prompt"/><el-button type="primary" :disabled="!referenceName" :loading="working" @click="create">创建任务</el-button></div>
  <div class="task-grid" v-loading="loading"><article v-for="task in tasks" :key="task.id" class="task-card panel"><div class="task-top"><div><span class="eyebrow">TASK {{ task.id }}</span><h3>{{ task.product_name }}</h3></div><el-tag :type="statusType(task.status)">{{ task.status }}</el-tag></div><div class="preview"><el-image v-if="task.result_url" :src="task.result_url" fit="cover"/><div v-else class="waiting">{{ task.status === 'pending' || task.status === 'processing' ? '等待生成' : '暂无预览' }}</div></div><dl><dt>参考图</dt><dd>{{ task.reference_name }}</dd><dt>审批</dt><dd>{{ approvalText(task.approval_status) }}{{ task.confirmed ? ' · 已人工确认' : '' }}</dd><dt v-if="task.error_summary">失败原因</dt><dd v-if="task.error_summary" class="danger">{{ task.error_summary }}</dd></dl><div class="task-actions"><el-button v-if="['no_key','timeout','failed','field_missing'].includes(task.status)" @click="action(task,'retry')">重试</el-button><el-button v-if="task.status==='completed'&&!task.confirmed" @click="action(task,'confirm')">人工确认</el-button><el-button v-if="task.status==='completed'&&task.confirmed&&task.approval_status==='draft'" type="primary" @click="action(task,'submit')">提交审批</el-button><el-button v-if="task.status==='completed'&&task.confirmed&&task.approval_status==='approved'" type="success" @click="action(task,'export')">导出素材</el-button><span v-if="task.approval_status!=='approved'" class="blocked">未批准，不能导出</span></div></article></div></section>
</template>
<script setup lang="ts">
import { onMounted, ref } from "vue"; import { ElMessage } from "element-plus"; import type { UploadFile } from "element-plus"; import { errorMessage } from "../api/client"; import { m2Api, type ApprovalStatus, type ImageTask, type ImageTaskStatus } from "../api/milestone2";
const tasks=ref<ImageTask[]>([]), loading=ref(false),working=ref(false),error=ref(""),referenceName=ref(""),referenceFile=ref<File>(),prompt=ref("");
async function refresh(){loading.value=true;try{tasks.value=await m2Api.listTasks()}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
function onFile(file:UploadFile){if(file.raw){referenceFile.value=file.raw;referenceName.value=file.name}}
async function create(){if(!referenceFile.value)return;working.value=true;try{const upload=await m2Api.uploadReference(1,referenceFile.value);await m2Api.createTask(1,upload.reference_name,prompt.value);referenceName.value="";referenceFile.value=undefined;prompt.value="";await refresh();ElMessage.success("图片任务已创建")}catch(e){error.value=errorMessage(e)}finally{working.value=false}}
async function action(task:ImageTask,action:"retry"|"confirm"|"submit"|"export"){try{const updated=await m2Api.taskAction(task.id,action);tasks.value=tasks.value.map(t=>t.id===updated.id?updated:t);ElMessage.success(action==="export"?"已导出素材并记录审计":"状态已更新")}catch(e){error.value=errorMessage(e)}}
function statusType(s:ImageTaskStatus){return (["completed"].includes(s)?"success":["failed","no_key","timeout","field_missing"].includes(s)?"danger":"warning") as "success"|"danger"|"warning"}
function approvalText(s:ApprovalStatus){return ({draft:"草稿",submitted:"待审批",approved:"已批准",rejected:"已拒绝"})[s]};onMounted(refresh);
</script>
<style scoped>
.notice{margin-bottom:14px}.new-task{display:grid;grid-template-columns:1.4fr auto auto minmax(180px,1fr) auto;gap:12px;align-items:center;margin-bottom:18px}.new-task p{color:var(--muted);font-size:12px;margin:5px 0 0}.file-name{font-size:12px;color:var(--muted)}.task-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px}.task-card{padding:14px}.task-top{display:flex;justify-content:space-between;gap:10px}.task-top h3{margin:4px 0 12px;font-size:16px}.preview{height:180px;background:#eef3ef;border-radius:4px;overflow:hidden}.preview :deep(.el-image){height:100%;width:100%}.waiting{height:100%;display:grid;place-items:center;color:var(--muted)}dl{display:grid;grid-template-columns:65px 1fr;gap:7px;margin:14px 0;font-size:13px}dt{color:var(--muted)}dd{margin:0}.danger{color:#b42318}.task-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.blocked{font-size:12px;color:var(--muted)}@media(max-width:900px){.new-task{grid-template-columns:1fr}}
</style>
