<template>
  <section>
    <div class="page-heading"><div><el-button link @click="router.push('/products')">← 返回商品列表</el-button><h1>{{ product?.name || '商品详情' }}</h1><p>{{ product?.category }} <span v-if="product?.brand">· {{ product.brand }}</span></p></div><el-button v-if="canEdit" type="primary" :loading="savingProduct" @click="saveProduct">保存商品信息</el-button></div>
    <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon class="notice" />
    <el-alert v-if="!canEdit" title="客服为只读访问：可使用已授权事实，但不能编辑商品、SKU、成本或毛利。" type="info" :closable="false" class="notice" />
    <el-skeleton v-if="loading" :rows="8" animated />
    <template v-else-if="product"><div class="layout"><div class="panel"><h2>商品事实</h2><el-form label-position="top"><el-form-item label="商品名称"><el-input v-model.trim="product.name" :disabled="!canEdit" /></el-form-item><el-form-item label="商品类目"><el-input v-model.trim="product.category" :disabled="!canEdit" /></el-form-item><el-form-item label="品牌"><el-input v-model.trim="product.brand" :disabled="!canEdit" /></el-form-item><el-form-item label="商品描述"><el-input v-model="product.description" type="textarea" :disabled="!canEdit" /></el-form-item></el-form></div>
      <div class="panel"><h2>SKU、成本与预估毛利</h2><p class="hint">预估毛利额 = 实收售价 − 六项成本；任何成本缺失或零售价时，显示“毛利待确认”。</p><el-collapse v-model="openSku"><el-collapse-item v-for="sku in product.skus" :key="sku.id" :name="String(sku.id)" :title="`${sku.sku_name} · 零售价 ¥${format(sku.price)}`"><div class="sku-grid"><el-form label-position="top"><el-form-item label="SKU 名称"><el-input v-model.trim="sku.sku_name" :disabled="!canEdit" /></el-form-item><el-form-item label="规格"><el-input v-model.trim="sku.spec" :disabled="!canEdit" /></el-form-item><el-form-item label="零售价（元）"><el-input-number v-model="sku.price" :min="0" :precision="2" controls-position="right" :disabled="!canEdit" /></el-form-item></el-form><div><h3>成本录入</h3><div class="cost-grid"><el-form-item v-for="field in fields" :key="field.key" :label="field.label" :error="fieldError(sku, field.key)"><el-input-number v-model="costsFor(sku)[field.key]" :min="0" :precision="2" :placeholder="'未录入'" controls-position="right" :disabled="!canEdit" @change="refreshMargin(sku)" /></el-form-item></div><div v-if="canEdit" class="cost-actions"><el-button type="primary" plain :loading="savingSku===sku.id" @click="saveCosts(sku)">保存成本</el-button></div></div></div><div class="margin" :class="marginFor(sku).status"><div><span>预估毛利状态</span><strong>{{ marginFor(sku).status === 'ready' ? '已计算' : '毛利待确认' }}</strong></div><template v-if="marginFor(sku).status === 'ready'"><div><span>预估毛利额</span><strong>¥{{ format(marginFor(sku).estimated_gross_profit) }}</strong></div><div><span>预估毛利率</span><strong>{{ percent(marginFor(sku).estimated_gross_margin_rate) }}</strong></div></template><p v-else>请补全采购、包装、运费补贴、平台费、推广分摊和售后损失，并确认零售价大于 0；当前不产生任何调价结论。</p></div></el-collapse-item></el-collapse></div></div></template>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useProductStore, type CostFields, type MarginResult, type ProductItem, type SKUItem } from "../stores/product";
import { useAuthStore } from "../stores/auth";
import { errorMessage } from "../api/client";
const route=useRoute(), router=useRouter(), store=useProductStore(), auth=useAuthStore();
const product=ref<ProductItem|null>(null), loading=ref(true), error=ref(""), savingProduct=ref(false), savingSku=ref<number|undefined>(), openSku=ref<string[]>([]);
const canEdit=computed(()=>auth.user?.role === "admin" || auth.user?.role === "operator_content");
const costs=reactive<Record<number,CostFields>>({}), margins=reactive<Record<number,MarginResult>>({});
const fields=[{key:"purchase_cost",label:"采购成本"},{key:"packaging_cost",label:"包装成本"},{key:"shipping_subsidy",label:"运费补贴"},{key:"platform_fee",label:"平台费"},{key:"promotion_allocation",label:"推广分摊"},{key:"after_sales_loss",label:"售后损失"}] as const;
onMounted(async()=>{try{product.value=await store.getProduct(Number(route.params.id));openSku.value=product.value.skus.map(s=>String(s.id));product.value.skus.forEach(s=>{if(s.id){costs[s.id]={...s.costs};refreshMargin(s)}})}catch(e){error.value=errorMessage(e)}finally{loading.value=false}});
function costsFor(s:SKUItem){return costs[s.id||0]||(costs[s.id||0]={})}
function localMargin(s:SKUItem):MarginResult{const values=fields.map(f=>costsFor(s)[f.key]);if(Number(s.price)<=0||values.some(v=>v===undefined))return{status:"pending_confirmation",estimated_gross_profit:null,estimated_gross_margin_rate:null};const total=values.reduce<number>((sum,value)=>sum+Number(value),0), profit=Number(s.price)-total;return{status:"ready",estimated_gross_profit:+profit.toFixed(2),estimated_gross_margin_rate:+(profit/Number(s.price)).toFixed(4),total_cost:total}}
function marginFor(s:SKUItem){return margins[s.id||0]||localMargin(s)} function refreshMargin(s:SKUItem){if(s.id)margins[s.id]=localMargin(s)}
function fieldError(s:SKUItem,key:keyof CostFields){const value=costsFor(s)[key];return value!==undefined&&Number(value)<0?"成本不能为负数":""}
async function saveCosts(s:SKUItem){if(!s.id||!canEdit.value)return;error.value="";if(fields.some(f=>Number(costsFor(s)[f.key])<0)){error.value="成本不能为负数";return;}savingSku.value=s.id;try{await store.saveCosts(s.id,costsFor(s));margins[s.id]=await store.getMargin(s.id)}catch(e){error.value=errorMessage(e)}finally{savingSku.value=undefined}}
async function saveProduct(){if(!product.value||!canEdit.value)return;error.value="";if(!product.value.name||!product.value.category){error.value="商品名称和类目不能为空";return;}savingProduct.value=true;try{await store.updateProduct(product.value.id,{name:product.value.name,category:product.value.category,brand:product.value.brand,description:product.value.description,skus:product.value.skus})}catch(e){error.value=errorMessage(e)}finally{savingProduct.value=false}}
function format(v:number|null|undefined){return v===null||v===undefined?"--":Number(v).toFixed(2)} function percent(v:number|null){return v===null?"--":`${(v*100).toFixed(2)}%`}
</script>
<style scoped>.notice{margin-bottom:14px}.layout{display:grid;grid-template-columns:minmax(260px,.75fr) minmax(0,1.5fr);gap:16px}.panel h2{margin-top:0;font-size:16px}.hint{font-size:13px;color:#66766f}.sku-grid{display:grid;grid-template-columns:minmax(190px,.7fr) minmax(300px,1.3fr);gap:24px}.cost-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 12px}.cost-actions{margin-top:8px}.margin{display:flex;gap:28px;align-items:center;background:#e5f3ed;border-left:3px solid #007d61;padding:12px;margin-top:16px}.margin span{display:block;color:#66766f;font-size:12px}.margin strong{display:block;margin-top:3px}.margin.pending_confirmation{display:block;background:#fff8e8;border-color:#9a6800;color:#735000}.margin p{margin:8px 0 0}@media(max-width:900px){.layout,.sku-grid{grid-template-columns:1fr}.cost-grid{grid-template-columns:1fr}.margin{display:block}.margin>div{margin:8px 0}}</style>
